### ISSUE TITLE
SparkFun Micro 6DoF IMU - ISM330DHCX (Qwiic): adding "stamp type" pins? (general for all micro boards)

### ISSUE THREAD

**Issue by jerabaul29** [sparkfun/SparkFun_Qwiic_6DoF_ISM330DHCX#1]
Thanks for amazing boards as usual :) . A small thought: would it be possible to actually break out the key pins on the chip (power, I2C, maybe interrupts and a couple more, you can evaluate which may be most valuable for different uses :) ) on the breakout board, possibly as "side stamp type pins" if there is no space to put through holes pin holes? I.e., something similar to for example:

![Screenshot from 2022-08-03 16-27-28](https://user-images.githubusercontent.com/8382834/182633721-6f464c9e-c5f7-49b1-ad2c-11a2377cdc65.png)

This comment would be applicable to all "Micro" breakouts. The advantage then is that the "Micro" boards could also be soldered on a master PCB easily if wanted, extending possibilities of use.

**Comment by edspark** [comment]
Thank you for the suggestion! We had a discussion while developing the Qwiic Micro about exactly this. We decided against it in the end, but if we see a strong desire for this addition we'll definitely revisit it.

**Comment by jerabaul29** [comment]
Thanks for the explanation :) . Just curious, what were the cons Vs pros on this? I only see pros, but certainly missing something :) .

**Comment by edspark** [comment]
We wanted the smallest board we could manage and those castellated leads ("side stamp type pins" as you called them) eat into the design space quite a bit.  We would have ended up with a larger PCB then we were shooting for.

**Comment by jerabaul29** [comment]
Understand, thanks :) .
